# Generated by Django 4.0.1 on 2022-01-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut adoptador')),
                ('pnombre', models.CharField(max_length=20, verbose_name='Primer nombre')),
                ('snombre', models.CharField(max_length=20, verbose_name='Segundo nombre')),
                ('papellido', models.CharField(max_length=20, verbose_name='Primer apellido')),
                ('sapellido', models.CharField(max_length=20, verbose_name='Segundo apellido')),
                ('edad', models.CharField(max_length=2, verbose_name='Edad')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contrasena')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idRaza', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Raza')),
                ('nombreRaza', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id_chip', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Chip')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre gato')),
                ('color', models.CharField(max_length=20, verbose_name='Color gato')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('edad', models.CharField(max_length=2, verbose_name='Edad de gato')),
                ('Descripcion', models.CharField(max_length=1000, verbose_name='Descripción del gato')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raza')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
